server:
    port: 8888
spring:
    application:
        name: config-service
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                  search-locations: file://${user.home}/IdeaProjects/native-file-repo
                git:
#                    uri: file:///Users/zion/IdeaProjects/git-local-repo
                    uri: https://github.com/sieun0322/spring-cloud-config
                    default-label: master
management:
    endpoints:
        web:
            exposure:
                include: health, refresh, busrefresh